### ISSUE TITLE
Issue with 0.5.0 version publishing

### ISSUE THREAD

**Issue by ctjhoa** [simplabs/eslint-plugin-ember-concurrency#160]
Even if github action is supposed to have publish 0.5.0 version
https://github.com/simplabs/eslint-plugin-ember-concurrency/runs/3892918019?check_suite_focus=true

Version 0.5.0 is not available in npm registry
https://www.npmjs.com/package/eslint-plugin-ember-concurrency?activeTab=versions

**Comment by Mikek2252** [comment]
Hello!
Thanks for pointing this out, i incorrectly published 0.5.0 so i had to unpublish but the new release wasnt able to replace the previous version. I have now released a new minor version 0.5.1 that can be used.

This could solve your issue.
